image: alpine/git:latest

pipelines:
  default:
    - step:
        name: Sync Mirror to GitHub
        script:
          # 1. Push everything from the current cloned directory directly to GitHub
          - git push --mirror git@github.com:awaisahmad-innovinci/blackbox.git
